[package]
name = "methods-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[build-dependencies]
risc0-build = "0.10"

[dependencies]
risc0-zkvm-guest = "0.10"
sha2 = "0.10.2"
hex = "0.4"
hex-literal = "0.3.4"
serde = "1.0"
